AWSTemplateFormatVersion: "2010-09-09"
Description: Template to create EC2 instance
Parameters:
  InstanceType:
      Description: WebServer EC2 instance type
      Type: String

  AMIID:
    Description: The EC2 AMI id
    Type: String
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: !Ref AMIID
      InstanceType: !Ref InstanceType

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: joel-demo-05-10-22-demo